Add OpenCascade.js
torch2424/made-with-webassembly pull request #96
Opened 2022-04-04 08:57 UTC by donalffons

Great website, thanks a lot for building an maintaining it!

With this PR, I would like to add `OpenCascade.js` - a port of the OpenCascade CAD library that can be used via WebAssembly.

2022-04-05 00:01 UTC, torch2424 requested changes
> Great website, thanks a lot for building an maintaining it!

You are welcome! Thank you for checking it out, and opening a PR! 😄 🎉 

> With this PR, I would like to add OpenCascade.js - a port of the OpenCascade CAD library that can be used via WebAssembly.

Woahhhh! That's an awesome project! 😄 Thanks for submitting it! 🎉 

---

So I only have one quick change request, it looks like your logo URL is broken, once that is fixed, I'll approve and merge! 😄 🎉

2022-04-05 05:16 UTC, donalffons commented on showcase/opencascadejs.md
> +logo_url: https://github.com/donalffons/opencascade.js/blob/master/images/logo%20no%20text.svg
Thanks for the catch! I just pushed a fix.

2022-04-06 09:32 UTC, donalffons reviewed
fixed url

2022-04-06 16:43 UTC, torch2424 approved these changes
Awesome! Thank you very much for the submission! 😄 🎉

2022-04-06 16:43 UTC, merged